export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const USER_UPDATE = "USER_UPDATE";
export const GET_MODULE2 = "GET_MODULE2";
export const UPDATE_BASELINE = "UPDATE_BASELINE";
export const UPDATE_ECONOMIC_PARAMETERS = "UPDATE_ECONOMIC_PARAMETERS";