import { GET_MODULE2, UPDATE_BASELINE, UPDATE_ECONOMIC_PARAMETERS, UPDATE_SOLAR_PV } from "../actions/types";
import EnergyManagementSystem from "../components/module2/EnergyManagementSystem";

const initialState = {
    baseline: {
        averageAnnualElectricityConsumption: "",
        averageAnnualGasConsumption: "",
        emissionFactorGridElectricity: "0.284",
        emissionFactorForGridGas: "0.18",
        annualOperationalEmissionsForGridElectricity: "",
        annualOperationalEmissionsForGridGas: "",
        totalBaselineEmissions: "",
        isComplete: false
    },
    economicParameters: {
        unitPriceOfElectricity: "0.248",
        unitPriceOfGas: "0.0603",
        yearsOfAbatement: "10",
        discountRate: "5",
        isComplete: false
    },
    solarPV: {
        averageAnnualElectricityRequirements: "",
        percentAnnualElectricityFromPV: "80",
        location: "Coventry",
        latitudeLongitude: "",
        electricityGeneratedPVSystem: "",
        annualElectricityGenerationSelectedLocation: "",
        annualSolarInsolationSelectedLocation: "",
        solarModuleEfficiency: "",
        gHGEmissionsElectricityPVSystem: "",
        annualOperationalEmissionSavings: "",
        totalOperationalEmissionSavingsAbatementPeriod: "",
        unitInstallationCostPVSystem: "",
        initialInvestmentPVSystem: "",
        annualElectricityInsteadOfGrid: "",
        sizeOfPVSystem: "",
        areaOfPVSystem: "",
        annualOperationalCostSavings: "",
        netPresentValueOperationalEnergy: "",
        totalOperationalEmissionSavingsAbatementPeriodInTon: "",
        costEffectivenessOperationalEmission: "",
        isComplete: false
    },
    led: {
        currentTypeOfLighting: "",
        currentLightingPowerRating:"",
        numberOfUnits:"",
        dailyUsage:"",
        numberOfOperationalDaysInaYear:"",
        annualUsage:"",
        lEDPowerRating:"",
        unitCostForLED:"",
        initialInvestmentForLEDs:"",
        costofElectricityWithCurrentLighting:"",
        costOfElectricityWithLEDs:"",
        annualOperationalEmissionSavings:"",
        totalOperationalEmissionSavingsAcrossAbatementPeriod:"",
        annualElectricityConsumptionWithCurrentLighting:"",
        annualElectricityConsumptionWithLEDs:"",
        annualElectricitySavingsWithLEDs:"",
        annualOperationalCostSavings:"",
        netPresentValueOfOperationalEnergyCostSavings:"",
        totalOperationalEmissionSavingsAcrossAbatementPeriodTon:"",
        costEffectivenessConsideringOperationalEmissionSavingsOnly:"",

    },
    passiveInfraredSensor: {
        numberOfLamps:"",
        wattageOfLamp:"",
        numberOfDaysInYear:"",
        estimatedHoursONPerDay:"",
        estimatedHoursOccupiedPerDay:"",
        areaOfIndustrialFacility:"",
        detectionRangeOfPIRSensors:"",
        numberOfPIRSensors:"",
        annualElectricityConsumptionWithoutPirSensor:"",
        annualElectricityConsumptionWithPirSensorInstalled:"",
        annualElectricitySavingsWithPirSensors:"",
        unitCostOfPirSensor:"",
        initialInvestmentForPir:"",
        annualOperationalCostSavings:"",
        netPresentValueOfOperationalEnergyCostSaings:"",
        annualOperationalEmissionSavings:"",
        totalOperationalEmissionSavingsAcrossAbatementPeriod:"",
        costEffectivenessConsideringOperationalEmissionSavingsOnly:"",
        totalOperationalEmissionSavingsAcrossAbatementPeriodTon:"",
    },
    smartMetersElectricity:{
        averageAnnualElectricityConsumption:"",
        currentLightingPowerRating:"",
        averageElectricitySavingsIncentivisedUsingSmartMeter:"",
        annualElectricitySavingsWithSmartMeters:"",
        initialInvestmentForElectricitySmartMeter:"",
        annualOperationalCostSavings:"",
        netPresentValueOfOperationalEnergyCostSavings:"",
        annualOperationalEmissionSavings:"",
        totalOperationalEmissionSavingsAcrossAbatementPeriod:"",
        totalOperationalEmissionSavingsAcrossAbatementPeriodTon:"",
        costEffectivenessConsideringOperationalEmissionSavingsOnly:"",
    },
    smartMetersGas:{
        averageAnnualGasConsumption:"",
        averageGasSavingsIncentivisedUsingSmartMeter:"",
        annualGasConsumptionWithSmartMeters:"",
        initialInvestmentForGasSmartMeter:"",
        annualOperationalCostSavings:"",
        netPresentValueOfOperationalEnergyCostSavings:"",
        annualOperationalEmissionSavings:"",
        totalOperationalEmissionSavingsAcrossAbatementPeriod:"",
        totalOperationalEmissionSavingsAcrossAbatementPeriodTon:"",
        costEffectivenessConsideringOperationalEmissionSavingsOnly:"",
    },
    voltageOptimisation:{
        averageAnnualElectricityConsumption:"",
        averageElectricitySavingsUsingVoltageOptimisation:"",
        annualElectricitySavingsWithVoltageOptimisation:"",
        annualOperationalCostSavings:"",
        initialInvestmentForVoltageOptimisation:"",
        netPresentValueOfOperationalEnergyCostSavings:"",
        annualOperationalEmissionSavings:"",
        totalOperationalEmissionSavingsAcrossAbatementPeriod:"",
        totalOperationalEmissionSavingsAcrossAbatementPeriodTon:"",
        costEffectivenessConsideringOperationalEmissionSavingsOnly:"",
    },
    energyManagementSystem:{
        averageAnnualElectricityConsumption:"",
        averageAnnualGasConsumption:"",
        averageElectricitySavingsIncentivisedUsingBEMS:"",
        averageGasSavingsIncentivisedUsingBEMS:"",
        annualElectricitySavingsWithBEMS:"",
        annualGasSavingsWithBEMS:"",
        initialInvestmentForBEMS:"",
        annualOperationalElectricityCostSavings:"",
        annualOperationalGasCostSavings:"",
        totalAnnualOperationalCostSavings:"",
        totalOperationalEmissionSavingsAbatementPeriod:"",
        netPresentValueOfOperationalEnergyCostSavings:"",
        gHGEmissionsSavingsForElectricityWithBEMS:"",
        gHGEmissionsSavingsForGasWithBEMS:"",
        annualOperationalEmissionSavings:"",
        totalOperationalEmissionSavingsAcrossAbatementPeriodTon:"",
        costEffectivenessConsideringOperationalEmissionSavingsOnly:"",
    },
    solarThermal:{
        averageAnnualGasRequirements:"",
        heatDemandToBeTakenFromSolarThermalSystem:"",
        location:"",
        lattitudeLongitude:"",
        existingBoilerEfficiency:"",
        incidentSolarIrradiation:"",
        solarIrradiation:"",
        opticalEfficiency:"",
        firstOrderEfficiencyCoefficient:"",
        secondOrderEfficiencyCoefficient:"",
        ambientTemperature:"",
        inletTemperature:"",
        outletTemperature:"",
        collectorTemperature:"",
        efficiencyOfSolarThermalSystem:"",
        capacityOfSolarThermalSystem:"",
        annualGridGasSavingInPresenceOfSolarThermalSystem:"",
        sizeOfSolarThermalSystem:"",
        unitInstallationCostOfSolarThermalSystem:"",
        initialInvestmentForSolarThermalSystem:"",
        unitPriceOfGridGas:"",
        annualOperationalCostSavings:"",
        netPresentValueOfOperationalEnergyCostSavings:"",
        emissionFactorOfGridGas:"",
        annualOperationalEmissionSavings:"",
        totalOperationalEmissionSavingsAcrossAbatementPeriod:"",
        totalOperationalEmissionSavingsAcrossAbatementPeriodTon:"",
    },
    industrialHeatPump:{
        averageAnnualGasRequirements:"",
        heatLoadIsAtTemperaturesBelow100C:"",
        heatLoadIsAtTemperaturesBetween100C150C:"",
        lattitudeLongitude:"",
        existingBoilerEfficiency:"",
        hoursOfHeatDemand:"",
        annualHeatLoad:"",
        annualGridGasSavingInPresenceOfIHP1:"",
        heatSourceTemperature:"",
        heatSinkTemperature:"",
        temperatureLift:"",
        refrigerant:"",
        coefficientOfPerformanceOfIHP1:"",
        electricityInput:"",
        annualGridGasSavingInPresenceOfIHP2:"",
        coefficientOfPerformanceOfIHP2:"",
        electricityInputForIHP2:"",
        sizeOfIndustrialHeatPump1:"",
        annualElectricityInputToIHP1:"",
        sizeOfIndustrialHeatPump2:"",
        annualElectricityInputToIHP2:"",
        unitInstallationCostOfIHP:"",
        initialInvestmentForIHP1:"",
        initialInvestmentForIHP2:"",
        unitPriceOfElectricity:"",
        annualCostOfElectricityForIHP1:"",
        annualCostOfElectricityForIHP2:"",
        unitPriceOfGridGas:"",
        annualCostSavingsForGridGas:"",
        annualCostOfElectricityForIHPs:"",
        annualOperationalCostSavings:"",
        netPresentValueOfOperationalEnergyCostSavings:"",
        emissionFactorOfGridGas:"",
        emissionFactorOfElectricityUsedForIHPs:"",
        gHGEmissionsForHeatInAbsenceOfIHP:"",
        gHGEmissionsForHeatInPresenceOfIHP:"",
        annualOperationalEmissionSavings:"",
        totalOperationalEmissionSavingsAcrossAbatementPeriod:"",
        totalOperationalEmissionSavingsAcrossAbatementPeriodTon:"",
        costEffectivenessConsideringOperationalEmissionSavingsOnly:"",
        
    }

};

export default function (state = initialState, action) {
    const { type, payload } = action;

    switch (type) {
        case GET_MODULE2:
            return { data: payload };
        case UPDATE_BASELINE:
            return {
                ...state,
                baseline: payload
            }
        case UPDATE_ECONOMIC_PARAMETERS:
            return {
                ...state,
                economicParameters: payload
            }
        case UPDATE_SOLAR_PV:
            return {
                ...state,
                solarPV: payload
            }

        default:
            return state;
    }
}